//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizzaData.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierLog
    {
        public int id { get; set; }
        public Nullable<System.DateTime> openingDate { get; set; }
        public Nullable<System.DateTime> closingDate { get; set; }
        public decimal initialBalance { get; set; }
        public decimal ordersCashin { get; set; }
        public Nullable<decimal> miscellaneousCashin { get; set; }
        public decimal supplierOrderCashout { get; set; }
        public decimal miscellaneousCashout { get; set; }
        public decimal finalBalance { get; set; }
        public string createdBy { get; set; }
        public Nullable<byte> status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
