//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizzaData.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColonyCatalog
    {
        public int idColony { get; set; }
        public string code { get; set; }
        public string settlement { get; set; }
        public string typeSettlement { get; set; }
        public string municipality { get; set; }
        public string state { get; set; }
        public string city { get; set; }
    }
}
