//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashin
    {
        public int cashinId { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public decimal total { get; set; }
    }
}
