//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseOrder()
        {
            this.HomeOrderProducts = new HashSet<HomeOrderProduct>();
        }
    
        public int houseOrderId { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public decimal total { get; set; }
        public string clientName { get; set; }
        public string dealerId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Dealer Dealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeOrderProduct> HomeOrderProducts { get; set; }
    }
}
