//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalOrderProduct
    {
        public int internalOrderProductId { get; set; }
        public int amount { get; set; }
        public int internalOrderId { get; set; }
        public string productId { get; set; }
    
        public virtual InternalOrder InternalOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
