//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeSupply
    {
        public int recipeSupplyCode { get; set; }
        public int supplyAmount { get; set; }
        public string recipeID { get; set; }
        public string supplyId { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
