//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizzaServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalOrder()
        {
            this.InternalOrderProducts = new HashSet<InternalOrderProduct>();
        }
    
        public int internalOrderId { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public decimal total { get; set; }
        public string waiterName { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalOrderProduct> InternalOrderProducts { get; set; }
    }
}
